### ISSUE TITLE
No files published to npm in v0.5.0

### ISSUE THREAD

**Issue by danburzo** [node-fetch/fetch-charset-detection#131]
Hi there, we're trying to use this package with `node-fetch` v2.x to prepare for v3.x and we noticed there are [no files on npm](https://npmfs.com/package/fetch-charset-detection/0.5.0/) for the `v0.5.0` version.

**Comment by Richienb** [comment]
Fixed in [0.6.0](https://github.com/node-fetch/fetch-charset-detection/releases/tag/0.6.0)

**Comment by danburzo** [comment]
Thanks @Richienb! However, I seem to be getting an error when attempting `npm install fetch-charset-detection`. I'm on `node v16.5.0 / npm 7.19.1`.

<details>
<summary>Error output</summary>

```
npm install fetch-charset-detection
npm WARN tarball tarball data for fetch-charset-detection@https://registry.npmjs.org/fetch-charset-detection/-/fetch-charset-detection-0.6.0.tgz (sha512-lq5uuET/3AVAxkxHZRcgi0Vq5uQHVvwv6cxvQqQHIlmjLtAQ6eGhk2O9i8nSnZcQgrB8t+8bDPJGjBXDQQIWxA==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for fetch-charset-detection@https://registry.npmjs.org/fetch-charset-detection/-/fetch-charset-detection-0.6.0.tgz (sha512-lq5uuET/3AVAxkxHZRcgi0Vq5uQHVvwv6cxvQqQHIlmjLtAQ6eGhk2O9i8nSnZcQgrB8t+8bDPJGjBXDQQIWxA==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-lq5uuET/3AVAxkxHZRcgi0Vq5uQHVvwv6cxvQqQHIlmjLtAQ6eGhk2O9i8nSnZcQgrB8t+8bDPJGjBXDQQIWxA== integrity checksum failed when using sha512: wanted sha512-lq5uuET/3AVAxkxHZRcgi0Vq5uQHVvwv6cxvQqQHIlmjLtAQ6eGhk2O9i8nSnZcQgrB8t+8bDPJGjBXDQQIWxA== but got sha512-IiRQjHX+GhiLi8rbBwa65DThvvYw7hAa6UQHTanNskw9EFFNJkh5uMyrzXwOzNGLUD62s/wzIBVK+khlT97aOg==. (3400 bytes)
```

</details>

**Comment by Richienb** [comment]
I think that's an issue on npm's side

**Comment by danburzo** [comment]
Hi again, @Richienb. I'm switching to ESM downstream, and I'm hit by this error again. I have cloned the repo and republished under `@danburzo/fetch-charset-detection` and `npm install` works as expected. However, I'm still getting an integrity error for the original package. 

I'm not sure this can be fixed from the NPM side ([example issue from March](https://github.com/npm/cli/issues/2971)). Would you be willing to try republishing from under the latest npm 6.x / 7.x version?

**Comment by ahmed-sigmalux** [comment]
I'm running into this problem, too.
